package gui;

import dao.ProductDataInterface;
import dao.ProductDatabase;

/**
 *
 * @author dinjo998
 */
public class MainMenu extends javax.swing.JFrame {
	private final ProductDataInterface dao;
	/**
	 * Creates new form MainMenu
	 * @param dao
	 */
	public MainMenu(ProductDataInterface dao) {
		initComponents();
		this.dao = dao;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        playlistButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newRecipeButton = new javax.swing.JButton();
        createProfileButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel2.setText("Product Administration");
        jLabel2.setName("jLabel2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 240, 234));

        jLabel1.setBackground(new java.awt.Color(239, 240, 234));
        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 68, 41));
        jLabel1.setText("BONE");
        jLabel1.setName("jLabel1"); // NOI18N

        playlistButton.setBackground(new java.awt.Color(56, 133, 96));
        playlistButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        playlistButton.setForeground(new java.awt.Color(255, 255, 255));
        playlistButton.setText("P L A Y L I S T");
        playlistButton.setName("playlistButton"); // NOI18N
        playlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(94, 162, 129));
        profileButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        profileButton.setForeground(new java.awt.Color(255, 255, 255));
        profileButton.setText("P R O F I L E");
        profileButton.setName("profileButton"); // NOI18N
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(56, 133, 96));
        searchButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("S E A R C H");
        searchButton.setName("searchButton"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(239, 240, 234));
        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("APPLE");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setBackground(new java.awt.Color(239, 240, 234));
        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 68, 41));
        jLabel4.setText("TEA");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setBackground(new java.awt.Color(239, 240, 234));
        jLabel6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(174, 174, 173));
        jLabel6.setText("Bon Appétit ");
        jLabel6.setName("jLabel6"); // NOI18N

        newRecipeButton.setBackground(new java.awt.Color(94, 162, 129));
        newRecipeButton.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        newRecipeButton.setForeground(new java.awt.Color(255, 255, 255));
        newRecipeButton.setText("NEW R E C I P E");
        newRecipeButton.setName("newRecipeButton"); // NOI18N
        newRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecipeButtonActionPerformed(evt);
            }
        });

        createProfileButton.setBackground(new java.awt.Color(239, 240, 234));
        createProfileButton.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        createProfileButton.setForeground(new java.awt.Color(71, 71, 71));
        createProfileButton.setText("Create Profile");
        createProfileButton.setName("createProfileButton"); // NOI18N
        createProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(newRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createProfileButton))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createProfileButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void playlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistButtonActionPerformed
		ProductEditor newProduct = new ProductEditor(this, true, dao);
		newProduct.setLocationRelativeTo(this);
		newProduct.setVisible(true);
   }//GEN-LAST:event_playlistButtonActionPerformed

   private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		System.exit(0);
   }//GEN-LAST:event_searchButtonActionPerformed

   private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
      ProductReport report = new ProductReport(this, true, dao);
		report.setLocationRelativeTo(this);
		report.setVisible(true);
   }//GEN-LAST:event_profileButtonActionPerformed

    private void newRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecipeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRecipeButtonActionPerformed

    private void createProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createProfileButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProfileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton newRecipeButton;
    private javax.swing.JButton playlistButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
